# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "planter checkout customization"
client_id = "dad190a75b601432fddd07e0122ecf95"
application_url = "https://anyway-affiliated-tail-packet.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://anyway-affiliated-tail-packet.trycloudflare.com/auth/callback",
  "https://anyway-affiliated-tail-packet.trycloudflare.com/auth/shopify/callback",
  "https://anyway-affiliated-tail-packet.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "checkout-code-store.myshopify.com"
